### PR TITLE
Solution location anywhere

### PR DESCRIPTION
**Pull request by Tr4ncer**
Hello,

Here is a new contribution that focuses on the possibility of using this extension even with a solution that is not in the same path as projects.

I hope I have not made a mistake.

Here is the list of changes:
- Update of the AssemblyInfo and the version ([here](https://github.com/Tr4ncer/VsNamespaceFixer/commit/f99f636bc7a658084f2f29b987510cb0ea95c7e9#diff-d0bcf1febfbe66efea74108d2dc091e1), [here](https://github.com/Tr4ncer/VsNamespaceFixer/commit/f99f636bc7a658084f2f29b987510cb0ea95c7e9#diff-84a1af6862a7c6aefdfbc1a97cb92554), [here](https://github.com/Tr4ncer/VsNamespaceFixer/commit/f99f636bc7a658084f2f29b987510cb0ea95c7e9#diff-0bf2d684fc2049bd506da04006bc56ba)) 
- Typo ([here](https://github.com/Tr4ncer/VsNamespaceFixer/commit/f99f636bc7a658084f2f29b987510cb0ea95c7e9#diff-f564bc609c8063fc1c48aea857b34921))
- Migration in PackageReference (NuGet) ([here](https://github.com/Tr4ncer/VsNamespaceFixer/commit/f99f636bc7a658084f2f29b987510cb0ea95c7e9#diff-d82f257cb7eced013bdd42b0db51249c))
- Removing warnings ([example](https://github.com/Tr4ncer/VsNamespaceFixer/commit/f99f636bc7a658084f2f29b987510cb0ea95c7e9#diff-80f22e31742cdf9e27ce5220452982c3))
- Added reference to Microsoft.Build
- Using MsBuild to find the path to the solution ([example](https://github.com/Tr4ncer/VsNamespaceFixer/commit/f99f636bc7a658084f2f29b987510cb0ea95c7e9#diff-5e8c499e472020629e1e28a6b224b1f5), used [here](https://github.com/Tr4ncer/VsNamespaceFixer/commit/f99f636bc7a658084f2f29b987510cb0ea95c7e9#diff-99323ee53edeab0658c26f2337ef4e78))

### CODE REVIEW

**Comment by Tr4ncer** [comment]
I am under visual studio 2019. I hope it works properly in 2015 and 2017! :persevere:

**Comment by pauer24** [comment]
Wow!! Thanks a LOT!! Such an amount of changes! I'm already looking into
it. I just found some bug on a small feature I developed recently, so I
guess I'll upload both things at the same time.

Cheers, and thanks again for your help.

P.

**Comment by Tr4ncer** [comment]
> I think with this modification it won't be compatible with VS2015. Why did you change from [14.0 to [15.0 ?
> 
> And I've got the same question for the Microsoft.Framework.NDP Version, that you upgraded from [4.5 to [4.6

Effectively! It's a mistake, sorry!



> 
> Wow!! Thanks a LOT!! Such an amount of changes! I'm already looking into it. I just found some bug on a small feature I developed recently, so I guess I'll upload both things at the same time. Cheers, and thanks again for your help. P.

I'm happy to be useful. 

As I mentioned in the [thread](https://github.com/pauer24/VsNamespaceFixer/issues/17#issuecomment-509301925), I use msbuild to get information. This could be a starting point to solve this [issue](https://github.com/pauer24/VsNamespaceFixer/issues/17).

**Comment by pauer24** [comment]
Hello again, I've been reviewing the PR, and it won't work on the first try :(

The structure folder I've got is: 

- Main folder
  - project folder
  - solution folder

It crushes on GetSolutionFilePath method, because startupProject.GetSolutionFullPath() returns null.

Can you take a look at it, please? 

On the other hand, I will try this solution in VS2015, it has to work there, otherwise I cannot accept this feature at this cost.

Cheers!

**Comment by Tr4ncer** [comment]
After many tests, I did not succeed in reproducing the problem. I have no other version than 2019 for the moment. I do not have a null value returned.

If you wait a little I could be tested under vs2017 next week.

**Comment by pauer24** [comment]
Sure, I can wait, but the errors I found were using VS2019 like you :(

**Comment by Tr4ncer** [comment]
I tested under vs2017. I have no problem.
I added security for null values.

**Comment by Tr4ncer** [comment]
I corrected the minimum version of the extension. InstallationTarget >=14.0

By cons, I left the version of 4.6 framework (instead of 4.5) because the extension target framework is 4.6.

**Comment by pauer24** [comment]
Hey man, thanks a lot for these few changes. It was exactlly what I was
missing without knowing :)

The PR has been already aproved and the new version uploaded. It should be
able for the update anytime.

Cheers!!

P.

**Pull request merged**
